apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      initContainers:
        - name: init-uploads
          image: busybox:1.36
          command: ["sh", "-c", "mkdir -p /app/uploads/agent-logs"]
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
      containers:
        - name: nextjs-app
          image: shortcutjawad/nextjs-app:latest  
          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"

            # Database 
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/agentic_test_harness"

            - name: DIRECT_URL
              value: "postgresql://postgres:postgres@postgres-service:5432/agentic_test_harness"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt_secret

            - name: GOOGLE_GEMINI_API
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: gemini_api

            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: groq_api

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: openai_api

          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads

      volumes:
        - name: uploads-volume
          emptyDir: {}

